apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amongus-keycloak
  namespace: argocd
spec:
  project: 
  source:
    repoURL: https://github.com//.git
    targetRevision: main
    path: k8s
  destination:
    server: 
    namespace: 
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
