apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ values.repo | trim }}
  namespace: argocd
spec:
  project: {{ values.argocd_project }}
  source:
    repoURL: https://github.com/{{ values.owner }}/{{ values.repo | trim }}
    targetRevision: {{ values.app_branch }}
    path: {{ values.app_manifest_path }}
  destination:
    server: {{ values.cluster_server }}
    namespace: {{ values.cluster_namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
